schema_version = "1.0.0"

id = "trident"
version = "0.1.2"
name = "TRIDENT"
tagline = "3D UMAP/t-SNE embeddings into Blender"
maintainer = "Cristiano Cordì - cordi.cristiano@gmail.com"
type = "add-on"
license = ["SPDX:GPL-3.0-or-later"]

website = "https://github.com/c-cordi/TRIDENT"

tags = ["3D View", "Object"]

blender_version_min = "4.2.0"

[permissions]
files = "Read/write data files and build outputs"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.pyc",
  ".git/",
]